//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("InheritanceDepth4Model", "OE00", "O", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InheritanceDepth4.O), "E00", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InheritanceDepth4.E00), true)]

#endregion

namespace InheritanceDepth4
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InheritanceDepth4ModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InheritanceDepth4ModelContainer object using the connection string found in the 'InheritanceDepth4ModelContainer' section of the application configuration file.
        /// </summary>
        public InheritanceDepth4ModelContainer() : base("name=InheritanceDepth4ModelContainer", "InheritanceDepth4ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InheritanceDepth4ModelContainer object.
        /// </summary>
        public InheritanceDepth4ModelContainer(string connectionString) : base(connectionString, "InheritanceDepth4ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InheritanceDepth4ModelContainer object.
        /// </summary>
        public InheritanceDepth4ModelContainer(EntityConnection connection) : base(connection, "InheritanceDepth4ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<E00> E00Set
        {
            get
            {
                if ((_E00Set == null))
                {
                    _E00Set = base.CreateObjectSet<E00>("E00Set");
                }
                return _E00Set;
            }
        }
        private ObjectSet<E00> _E00Set;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<O> OSet
        {
            get
            {
                if ((_OSet == null))
                {
                    _OSet = base.CreateObjectSet<O>("OSet");
                }
                return _OSet;
            }
        }
        private ObjectSet<O> _OSet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the E00Set EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToE00Set(E00 e00)
        {
            base.AddObject("E00Set", e00);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOSet(O o)
        {
            base.AddObject("OSet", o);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E00")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E10))]
    [KnownTypeAttribute(typeof(E11))]
    public abstract partial class E00 : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OId
        {
            get
            {
                return _OId;
            }
            set
            {
                OnOIdChanging(value);
                ReportPropertyChanging("OId");
                _OId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OId");
                OnOIdChanged();
            }
        }
        private global::System.Int32 _OId;
        partial void OnOIdChanging(global::System.Int32 value);
        partial void OnOIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth4Model", "OE00", "O")]
        public O O
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth4Model.OE00", "O").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth4Model.OE00", "O").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<O> OReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth4Model.OE00", "O");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<O>("InheritanceDepth4Model.OE00", "O", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E10")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E20))]
    [KnownTypeAttribute(typeof(E21))]
    public abstract partial class E10 : E00
    {
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E11")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E22))]
    [KnownTypeAttribute(typeof(E23))]
    public abstract partial class E11 : E00
    {
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E20")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E30))]
    [KnownTypeAttribute(typeof(E31))]
    public abstract partial class E20 : E10
    {
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E21")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E32))]
    [KnownTypeAttribute(typeof(E33))]
    public abstract partial class E21 : E10
    {
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E22")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E34))]
    [KnownTypeAttribute(typeof(E35))]
    public abstract partial class E22 : E11
    {
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E23")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E36))]
    [KnownTypeAttribute(typeof(E37))]
    public abstract partial class E23 : E11
    {
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E30")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E30 : E20
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E30 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E30 CreateE30(global::System.Int32 id, global::System.Int32 oId)
        {
            E30 e30 = new E30();
            e30.Id = id;
            e30.OId = oId;
            return e30;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E31")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E31 : E20
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E31 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E31 CreateE31(global::System.Int32 id, global::System.Int32 oId)
        {
            E31 e31 = new E31();
            e31.Id = id;
            e31.OId = oId;
            return e31;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E32")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E32 : E21
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E32 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E32 CreateE32(global::System.Int32 id, global::System.Int32 oId)
        {
            E32 e32 = new E32();
            e32.Id = id;
            e32.OId = oId;
            return e32;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E33")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E33 : E21
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E33 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E33 CreateE33(global::System.Int32 id, global::System.Int32 oId)
        {
            E33 e33 = new E33();
            e33.Id = id;
            e33.OId = oId;
            return e33;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E34")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E34 : E22
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E34 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E34 CreateE34(global::System.Int32 id, global::System.Int32 oId)
        {
            E34 e34 = new E34();
            e34.Id = id;
            e34.OId = oId;
            return e34;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E35")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E35 : E22
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E35 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E35 CreateE35(global::System.Int32 id, global::System.Int32 oId)
        {
            E35 e35 = new E35();
            e35.Id = id;
            e35.OId = oId;
            return e35;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E36")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E36 : E23
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E36 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E36 CreateE36(global::System.Int32 id, global::System.Int32 oId)
        {
            E36 e36 = new E36();
            e36.Id = id;
            e36.OId = oId;
            return e36;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="E37")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E37 : E23
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E37 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E37 CreateE37(global::System.Int32 id, global::System.Int32 oId)
        {
            E37 e37 = new E37();
            e37.Id = id;
            e37.OId = oId;
            return e37;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth4Model", Name="O")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class O : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new O object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static O CreateO(global::System.Int32 id)
        {
            O o = new O();
            o.Id = id;
            return o;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth4Model", "OE00", "E00")]
        public EntityCollection<E00> E00Set
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<E00>("InheritanceDepth4Model.OE00", "E00");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<E00>("InheritanceDepth4Model.OE00", "E00", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
