//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("InheritanceDepth3Model", "OE00", "O", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InheritanceDepth3.O), "E00", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InheritanceDepth3.E00), true)]

#endregion

namespace InheritanceDepth3
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InheritanceDepth3ModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InheritanceDepth3ModelContainer object using the connection string found in the 'InheritanceDepth3ModelContainer' section of the application configuration file.
        /// </summary>
        public InheritanceDepth3ModelContainer() : base("name=InheritanceDepth3ModelContainer", "InheritanceDepth3ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InheritanceDepth3ModelContainer object.
        /// </summary>
        public InheritanceDepth3ModelContainer(string connectionString) : base(connectionString, "InheritanceDepth3ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InheritanceDepth3ModelContainer object.
        /// </summary>
        public InheritanceDepth3ModelContainer(EntityConnection connection) : base(connection, "InheritanceDepth3ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<E00> E00Set
        {
            get
            {
                if ((_E00Set == null))
                {
                    _E00Set = base.CreateObjectSet<E00>("E00Set");
                }
                return _E00Set;
            }
        }
        private ObjectSet<E00> _E00Set;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<O> OSet
        {
            get
            {
                if ((_OSet == null))
                {
                    _OSet = base.CreateObjectSet<O>("OSet");
                }
                return _OSet;
            }
        }
        private ObjectSet<O> _OSet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the E00Set EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToE00Set(E00 e00)
        {
            base.AddObject("E00Set", e00);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOSet(O o)
        {
            base.AddObject("OSet", o);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Model", Name="E00")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E10))]
    [KnownTypeAttribute(typeof(E11))]
    public abstract partial class E00 : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OId
        {
            get
            {
                return _OId;
            }
            set
            {
                OnOIdChanging(value);
                ReportPropertyChanging("OId");
                _OId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OId");
                OnOIdChanged();
            }
        }
        private global::System.Int32 _OId;
        partial void OnOIdChanging(global::System.Int32 value);
        partial void OnOIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth3Model", "OE00", "O")]
        public O O
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth3Model.OE00", "O").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth3Model.OE00", "O").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<O> OReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth3Model.OE00", "O");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<O>("InheritanceDepth3Model.OE00", "O", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Model", Name="E10")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E20))]
    [KnownTypeAttribute(typeof(E21))]
    public abstract partial class E10 : E00
    {
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Model", Name="E11")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E22))]
    [KnownTypeAttribute(typeof(E23))]
    public abstract partial class E11 : E00
    {
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Model", Name="E20")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E20 : E10
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E20 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E20 CreateE20(global::System.Int32 id, global::System.Int32 oId)
        {
            E20 e20 = new E20();
            e20.Id = id;
            e20.OId = oId;
            return e20;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Model", Name="E21")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E21 : E10
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E21 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E21 CreateE21(global::System.Int32 id, global::System.Int32 oId)
        {
            E21 e21 = new E21();
            e21.Id = id;
            e21.OId = oId;
            return e21;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Model", Name="E22")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E22 : E11
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E22 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E22 CreateE22(global::System.Int32 id, global::System.Int32 oId)
        {
            E22 e22 = new E22();
            e22.Id = id;
            e22.OId = oId;
            return e22;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Model", Name="E23")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E23 : E11
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E23 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E23 CreateE23(global::System.Int32 id, global::System.Int32 oId)
        {
            E23 e23 = new E23();
            e23.Id = id;
            e23.OId = oId;
            return e23;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Model", Name="O")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class O : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new O object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static O CreateO(global::System.Int32 id)
        {
            O o = new O();
            o.Id = id;
            return o;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth3Model", "OE00", "E00")]
        public EntityCollection<E00> E00Set
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<E00>("InheritanceDepth3Model.OE00", "E00");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<E00>("InheritanceDepth3Model.OE00", "E00", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
