//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("InheritanceDepth3Assoc2Model", "E00A00", "E00", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(InheritanceDepth3Assoc2.E00), "A00", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InheritanceDepth3Assoc2.A00), true)]
[assembly: EdmRelationshipAttribute("InheritanceDepth3Assoc2Model", "OE00", "O", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InheritanceDepth3Assoc2.O), "E00", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InheritanceDepth3Assoc2.E00), true)]
[assembly: EdmRelationshipAttribute("InheritanceDepth3Assoc2Model", "A11C00", "A11", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InheritanceDepth3Assoc2.A11), "C00", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InheritanceDepth3Assoc2.C00), true)]
[assembly: EdmRelationshipAttribute("InheritanceDepth3Assoc2Model", "A10B00", "A10", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InheritanceDepth3Assoc2.A10), "B00", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InheritanceDepth3Assoc2.B00), true)]

#endregion

namespace InheritanceDepth3Assoc2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InheritanceDepth3Assoc2ModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InheritanceDepth3Assoc2ModelContainer object using the connection string found in the 'InheritanceDepth3Assoc2ModelContainer' section of the application configuration file.
        /// </summary>
        public InheritanceDepth3Assoc2ModelContainer() : base("name=InheritanceDepth3Assoc2ModelContainer", "InheritanceDepth3Assoc2ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InheritanceDepth3Assoc2ModelContainer object.
        /// </summary>
        public InheritanceDepth3Assoc2ModelContainer(string connectionString) : base(connectionString, "InheritanceDepth3Assoc2ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InheritanceDepth3Assoc2ModelContainer object.
        /// </summary>
        public InheritanceDepth3Assoc2ModelContainer(EntityConnection connection) : base(connection, "InheritanceDepth3Assoc2ModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<E00> E00Set
        {
            get
            {
                if ((_E00Set == null))
                {
                    _E00Set = base.CreateObjectSet<E00>("E00Set");
                }
                return _E00Set;
            }
        }
        private ObjectSet<E00> _E00Set;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<A00> A00Set
        {
            get
            {
                if ((_A00Set == null))
                {
                    _A00Set = base.CreateObjectSet<A00>("A00Set");
                }
                return _A00Set;
            }
        }
        private ObjectSet<A00> _A00Set;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<B00> B00Set
        {
            get
            {
                if ((_B00Set == null))
                {
                    _B00Set = base.CreateObjectSet<B00>("B00Set");
                }
                return _B00Set;
            }
        }
        private ObjectSet<B00> _B00Set;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<O> OSet
        {
            get
            {
                if ((_OSet == null))
                {
                    _OSet = base.CreateObjectSet<O>("OSet");
                }
                return _OSet;
            }
        }
        private ObjectSet<O> _OSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<C00> C00Set
        {
            get
            {
                if ((_C00Set == null))
                {
                    _C00Set = base.CreateObjectSet<C00>("C00Set");
                }
                return _C00Set;
            }
        }
        private ObjectSet<C00> _C00Set;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the E00Set EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToE00Set(E00 e00)
        {
            base.AddObject("E00Set", e00);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the A00Set EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToA00Set(A00 a00)
        {
            base.AddObject("A00Set", a00);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the B00Set EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToB00Set(B00 b00)
        {
            base.AddObject("B00Set", b00);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOSet(O o)
        {
            base.AddObject("OSet", o);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the C00Set EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToC00Set(C00 c00)
        {
            base.AddObject("C00Set", c00);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="A00")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(A11))]
    [KnownTypeAttribute(typeof(A10))]
    [KnownTypeAttribute(typeof(A12))]
    public abstract partial class A00 : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dA00
        {
            get
            {
                return _dA00;
            }
            set
            {
                OndA00Changing(value);
                ReportPropertyChanging("dA00");
                _dA00 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dA00");
                OndA00Changed();
            }
        }
        private global::System.String _dA00;
        partial void OndA00Changing(global::System.String value);
        partial void OndA00Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> E00Id
        {
            get
            {
                return _E00Id;
            }
            set
            {
                OnE00IdChanging(value);
                ReportPropertyChanging("E00Id");
                _E00Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E00Id");
                OnE00IdChanged();
            }
        }
        private Nullable<global::System.Int32> _E00Id;
        partial void OnE00IdChanging(Nullable<global::System.Int32> value);
        partial void OnE00IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth3Assoc2Model", "E00A00", "E00")]
        public E00 E00
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<E00>("InheritanceDepth3Assoc2Model.E00A00", "E00").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<E00>("InheritanceDepth3Assoc2Model.E00A00", "E00").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<E00> E00Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<E00>("InheritanceDepth3Assoc2Model.E00A00", "E00");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<E00>("InheritanceDepth3Assoc2Model.E00A00", "E00", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="A10")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class A10 : A00
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new A10 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static A10 CreateA10(global::System.Int32 id)
        {
            A10 a10 = new A10();
            a10.Id = id;
            return a10;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dA10
        {
            get
            {
                return _dA10;
            }
            set
            {
                OndA10Changing(value);
                ReportPropertyChanging("dA10");
                _dA10 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dA10");
                OndA10Changed();
            }
        }
        private global::System.String _dA10;
        partial void OndA10Changing(global::System.String value);
        partial void OndA10Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth3Assoc2Model", "A10B00", "B00")]
        public EntityCollection<B00> B00Set
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<B00>("InheritanceDepth3Assoc2Model.A10B00", "B00");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<B00>("InheritanceDepth3Assoc2Model.A10B00", "B00", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="A11")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class A11 : A00
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new A11 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static A11 CreateA11(global::System.Int32 id)
        {
            A11 a11 = new A11();
            a11.Id = id;
            return a11;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dA11
        {
            get
            {
                return _dA11;
            }
            set
            {
                OndA11Changing(value);
                ReportPropertyChanging("dA11");
                _dA11 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dA11");
                OndA11Changed();
            }
        }
        private global::System.String _dA11;
        partial void OndA11Changing(global::System.String value);
        partial void OndA11Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth3Assoc2Model", "A11C00", "C00")]
        public EntityCollection<C00> C00Set
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<C00>("InheritanceDepth3Assoc2Model.A11C00", "C00");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<C00>("InheritanceDepth3Assoc2Model.A11C00", "C00", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="A12")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class A12 : A00
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new A12 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static A12 CreateA12(global::System.Int32 id)
        {
            A12 a12 = new A12();
            a12.Id = id;
            return a12;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dA12
        {
            get
            {
                return _dA12;
            }
            set
            {
                OndA12Changing(value);
                ReportPropertyChanging("dA12");
                _dA12 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dA12");
                OndA12Changed();
            }
        }
        private global::System.String _dA12;
        partial void OndA12Changing(global::System.String value);
        partial void OndA12Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="B00")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B00 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new B00 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="a10Id">Initial value of the A10Id property.</param>
        public static B00 CreateB00(global::System.Int32 id, global::System.Int32 a10Id)
        {
            B00 b00 = new B00();
            b00.Id = id;
            b00.A10Id = a10Id;
            return b00;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dB00
        {
            get
            {
                return _dB00;
            }
            set
            {
                OndB00Changing(value);
                ReportPropertyChanging("dB00");
                _dB00 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dB00");
                OndB00Changed();
            }
        }
        private global::System.String _dB00;
        partial void OndB00Changing(global::System.String value);
        partial void OndB00Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 A10Id
        {
            get
            {
                return _A10Id;
            }
            set
            {
                OnA10IdChanging(value);
                ReportPropertyChanging("A10Id");
                _A10Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("A10Id");
                OnA10IdChanged();
            }
        }
        private global::System.Int32 _A10Id;
        partial void OnA10IdChanging(global::System.Int32 value);
        partial void OnA10IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth3Assoc2Model", "A10B00", "A10")]
        public A10 A10
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<A10>("InheritanceDepth3Assoc2Model.A10B00", "A10").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<A10>("InheritanceDepth3Assoc2Model.A10B00", "A10").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<A10> A10Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<A10>("InheritanceDepth3Assoc2Model.A10B00", "A10");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<A10>("InheritanceDepth3Assoc2Model.A10B00", "A10", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="C00")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C00 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new C00 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dC00">Initial value of the dC00 property.</param>
        /// <param name="a11Id">Initial value of the A11Id property.</param>
        public static C00 CreateC00(global::System.Int32 id, global::System.String dC00, global::System.Int32 a11Id)
        {
            C00 c00 = new C00();
            c00.Id = id;
            c00.dC00 = dC00;
            c00.A11Id = a11Id;
            return c00;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dC00
        {
            get
            {
                return _dC00;
            }
            set
            {
                OndC00Changing(value);
                ReportPropertyChanging("dC00");
                _dC00 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("dC00");
                OndC00Changed();
            }
        }
        private global::System.String _dC00;
        partial void OndC00Changing(global::System.String value);
        partial void OndC00Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 A11Id
        {
            get
            {
                return _A11Id;
            }
            set
            {
                OnA11IdChanging(value);
                ReportPropertyChanging("A11Id");
                _A11Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("A11Id");
                OnA11IdChanged();
            }
        }
        private global::System.Int32 _A11Id;
        partial void OnA11IdChanging(global::System.Int32 value);
        partial void OnA11IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth3Assoc2Model", "A11C00", "A11")]
        public A11 A11
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<A11>("InheritanceDepth3Assoc2Model.A11C00", "A11").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<A11>("InheritanceDepth3Assoc2Model.A11C00", "A11").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<A11> A11Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<A11>("InheritanceDepth3Assoc2Model.A11C00", "A11");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<A11>("InheritanceDepth3Assoc2Model.A11C00", "A11", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="E00")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E10))]
    [KnownTypeAttribute(typeof(E11))]
    public abstract partial class E00 : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OId
        {
            get
            {
                return _OId;
            }
            set
            {
                OnOIdChanging(value);
                ReportPropertyChanging("OId");
                _OId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OId");
                OnOIdChanged();
            }
        }
        private global::System.Int32 _OId;
        partial void OnOIdChanging(global::System.Int32 value);
        partial void OnOIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth3Assoc2Model", "E00A00", "A00")]
        public EntityCollection<A00> A00Set
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<A00>("InheritanceDepth3Assoc2Model.E00A00", "A00");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<A00>("InheritanceDepth3Assoc2Model.E00A00", "A00", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth3Assoc2Model", "OE00", "O")]
        public O O
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth3Assoc2Model.OE00", "O").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth3Assoc2Model.OE00", "O").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<O> OReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth3Assoc2Model.OE00", "O");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<O>("InheritanceDepth3Assoc2Model.OE00", "O", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="E10")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E20))]
    [KnownTypeAttribute(typeof(E21))]
    public abstract partial class E10 : E00
    {
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="E11")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E22))]
    [KnownTypeAttribute(typeof(E23))]
    public abstract partial class E11 : E00
    {
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="E20")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E20 : E10
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E20 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E20 CreateE20(global::System.Int32 id, global::System.Int32 oId)
        {
            E20 e20 = new E20();
            e20.Id = id;
            e20.OId = oId;
            return e20;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="E21")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E21 : E10
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E21 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E21 CreateE21(global::System.Int32 id, global::System.Int32 oId)
        {
            E21 e21 = new E21();
            e21.Id = id;
            e21.OId = oId;
            return e21;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="E22")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E22 : E11
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E22 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E22 CreateE22(global::System.Int32 id, global::System.Int32 oId)
        {
            E22 e22 = new E22();
            e22.Id = id;
            e22.OId = oId;
            return e22;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="E23")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E23 : E11
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E23 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E23 CreateE23(global::System.Int32 id, global::System.Int32 oId)
        {
            E23 e23 = new E23();
            e23.Id = id;
            e23.OId = oId;
            return e23;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth3Assoc2Model", Name="O")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class O : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new O object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static O CreateO(global::System.Int32 id)
        {
            O o = new O();
            o.Id = id;
            return o;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth3Assoc2Model", "OE00", "E00")]
        public EntityCollection<E00> E00Set
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<E00>("InheritanceDepth3Assoc2Model.OE00", "E00");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<E00>("InheritanceDepth3Assoc2Model.OE00", "E00", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
