//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("InheritanceDepth5WideModel", "OE00", "O", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InheritanceDepth5Wide.O), "E00", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InheritanceDepth5Wide.E00), true)]

#endregion

namespace InheritanceDepth5Wide
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InheritanceDepth5WideModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InheritanceDepth5WideModelContainer object using the connection string found in the 'InheritanceDepth5WideModelContainer' section of the application configuration file.
        /// </summary>
        public InheritanceDepth5WideModelContainer() : base("name=InheritanceDepth5WideModelContainer", "InheritanceDepth5WideModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InheritanceDepth5WideModelContainer object.
        /// </summary>
        public InheritanceDepth5WideModelContainer(string connectionString) : base(connectionString, "InheritanceDepth5WideModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InheritanceDepth5WideModelContainer object.
        /// </summary>
        public InheritanceDepth5WideModelContainer(EntityConnection connection) : base(connection, "InheritanceDepth5WideModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<E00> E00Set
        {
            get
            {
                if ((_E00Set == null))
                {
                    _E00Set = base.CreateObjectSet<E00>("E00Set");
                }
                return _E00Set;
            }
        }
        private ObjectSet<E00> _E00Set;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<O> OSet
        {
            get
            {
                if ((_OSet == null))
                {
                    _OSet = base.CreateObjectSet<O>("OSet");
                }
                return _OSet;
            }
        }
        private ObjectSet<O> _OSet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the E00Set EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToE00Set(E00 e00)
        {
            base.AddObject("E00Set", e00);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOSet(O o)
        {
            base.AddObject("OSet", o);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E00")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E10))]
    [KnownTypeAttribute(typeof(E11))]
    public abstract partial class E00 : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE00
        {
            get
            {
                return _dE00;
            }
            set
            {
                OndE00Changing(value);
                ReportPropertyChanging("dE00");
                _dE00 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE00");
                OndE00Changed();
            }
        }
        private global::System.String _dE00;
        partial void OndE00Changing(global::System.String value);
        partial void OndE00Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OId
        {
            get
            {
                return _OId;
            }
            set
            {
                OnOIdChanging(value);
                ReportPropertyChanging("OId");
                _OId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OId");
                OnOIdChanged();
            }
        }
        private global::System.Int32 _OId;
        partial void OnOIdChanging(global::System.Int32 value);
        partial void OnOIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth5WideModel", "OE00", "O")]
        public O O
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth5WideModel.OE00", "O").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth5WideModel.OE00", "O").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<O> OReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<O>("InheritanceDepth5WideModel.OE00", "O");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<O>("InheritanceDepth5WideModel.OE00", "O", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E10")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E20))]
    [KnownTypeAttribute(typeof(E21))]
    public abstract partial class E10 : E00
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE10
        {
            get
            {
                return _dE10;
            }
            set
            {
                OndE10Changing(value);
                ReportPropertyChanging("dE10");
                _dE10 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE10");
                OndE10Changed();
            }
        }
        private global::System.String _dE10;
        partial void OndE10Changing(global::System.String value);
        partial void OndE10Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E11")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E22))]
    [KnownTypeAttribute(typeof(E23))]
    public abstract partial class E11 : E00
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE11
        {
            get
            {
                return _dE11;
            }
            set
            {
                OndE11Changing(value);
                ReportPropertyChanging("dE11");
                _dE11 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE11");
                OndE11Changed();
            }
        }
        private global::System.String _dE11;
        partial void OndE11Changing(global::System.String value);
        partial void OndE11Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E20")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E30))]
    [KnownTypeAttribute(typeof(E31))]
    public abstract partial class E20 : E10
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE20
        {
            get
            {
                return _dE20;
            }
            set
            {
                OndE20Changing(value);
                ReportPropertyChanging("dE20");
                _dE20 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE20");
                OndE20Changed();
            }
        }
        private global::System.String _dE20;
        partial void OndE20Changing(global::System.String value);
        partial void OndE20Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E21")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E32))]
    [KnownTypeAttribute(typeof(E33))]
    public abstract partial class E21 : E10
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE21
        {
            get
            {
                return _dE21;
            }
            set
            {
                OndE21Changing(value);
                ReportPropertyChanging("dE21");
                _dE21 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE21");
                OndE21Changed();
            }
        }
        private global::System.String _dE21;
        partial void OndE21Changing(global::System.String value);
        partial void OndE21Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E22")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E34))]
    [KnownTypeAttribute(typeof(E35))]
    public abstract partial class E22 : E11
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE22
        {
            get
            {
                return _dE22;
            }
            set
            {
                OndE22Changing(value);
                ReportPropertyChanging("dE22");
                _dE22 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE22");
                OndE22Changed();
            }
        }
        private global::System.String _dE22;
        partial void OndE22Changing(global::System.String value);
        partial void OndE22Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E23")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E36))]
    [KnownTypeAttribute(typeof(E37))]
    public abstract partial class E23 : E11
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE23
        {
            get
            {
                return _dE23;
            }
            set
            {
                OndE23Changing(value);
                ReportPropertyChanging("dE23");
                _dE23 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE23");
                OndE23Changed();
            }
        }
        private global::System.String _dE23;
        partial void OndE23Changing(global::System.String value);
        partial void OndE23Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E30")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E40))]
    [KnownTypeAttribute(typeof(E41))]
    [KnownTypeAttribute(typeof(E42))]
    public abstract partial class E30 : E20
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE30
        {
            get
            {
                return _dE30;
            }
            set
            {
                OndE30Changing(value);
                ReportPropertyChanging("dE30");
                _dE30 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE30");
                OndE30Changed();
            }
        }
        private global::System.String _dE30;
        partial void OndE30Changing(global::System.String value);
        partial void OndE30Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E31")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E43))]
    [KnownTypeAttribute(typeof(E44))]
    [KnownTypeAttribute(typeof(E45))]
    public abstract partial class E31 : E20
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE31
        {
            get
            {
                return _dE31;
            }
            set
            {
                OndE31Changing(value);
                ReportPropertyChanging("dE31");
                _dE31 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE31");
                OndE31Changed();
            }
        }
        private global::System.String _dE31;
        partial void OndE31Changing(global::System.String value);
        partial void OndE31Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E32")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E46))]
    [KnownTypeAttribute(typeof(E47))]
    [KnownTypeAttribute(typeof(E48))]
    public abstract partial class E32 : E21
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE32
        {
            get
            {
                return _dE32;
            }
            set
            {
                OndE32Changing(value);
                ReportPropertyChanging("dE32");
                _dE32 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE32");
                OndE32Changed();
            }
        }
        private global::System.String _dE32;
        partial void OndE32Changing(global::System.String value);
        partial void OndE32Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E33")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E49))]
    [KnownTypeAttribute(typeof(E410))]
    [KnownTypeAttribute(typeof(E411))]
    public abstract partial class E33 : E21
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE33
        {
            get
            {
                return _dE33;
            }
            set
            {
                OndE33Changing(value);
                ReportPropertyChanging("dE33");
                _dE33 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE33");
                OndE33Changed();
            }
        }
        private global::System.String _dE33;
        partial void OndE33Changing(global::System.String value);
        partial void OndE33Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E34")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E412))]
    [KnownTypeAttribute(typeof(E413))]
    [KnownTypeAttribute(typeof(E414))]
    public abstract partial class E34 : E22
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE34
        {
            get
            {
                return _dE34;
            }
            set
            {
                OndE34Changing(value);
                ReportPropertyChanging("dE34");
                _dE34 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE34");
                OndE34Changed();
            }
        }
        private global::System.String _dE34;
        partial void OndE34Changing(global::System.String value);
        partial void OndE34Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E35")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E415))]
    [KnownTypeAttribute(typeof(E416))]
    [KnownTypeAttribute(typeof(E417))]
    public abstract partial class E35 : E22
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE35
        {
            get
            {
                return _dE35;
            }
            set
            {
                OndE35Changing(value);
                ReportPropertyChanging("dE35");
                _dE35 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE35");
                OndE35Changed();
            }
        }
        private global::System.String _dE35;
        partial void OndE35Changing(global::System.String value);
        partial void OndE35Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E36")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E418))]
    [KnownTypeAttribute(typeof(E419))]
    [KnownTypeAttribute(typeof(E420))]
    public abstract partial class E36 : E23
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE36
        {
            get
            {
                return _dE36;
            }
            set
            {
                OndE36Changing(value);
                ReportPropertyChanging("dE36");
                _dE36 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE36");
                OndE36Changed();
            }
        }
        private global::System.String _dE36;
        partial void OndE36Changing(global::System.String value);
        partial void OndE36Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E37")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(E421))]
    [KnownTypeAttribute(typeof(E422))]
    [KnownTypeAttribute(typeof(E423))]
    public abstract partial class E37 : E23
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE37
        {
            get
            {
                return _dE37;
            }
            set
            {
                OndE37Changing(value);
                ReportPropertyChanging("dE37");
                _dE37 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE37");
                OndE37Changed();
            }
        }
        private global::System.String _dE37;
        partial void OndE37Changing(global::System.String value);
        partial void OndE37Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E40")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E40 : E30
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E40 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E40 CreateE40(global::System.Int32 id, global::System.Int32 oId)
        {
            E40 e40 = new E40();
            e40.Id = id;
            e40.OId = oId;
            return e40;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE40
        {
            get
            {
                return _dE40;
            }
            set
            {
                OndE40Changing(value);
                ReportPropertyChanging("dE40");
                _dE40 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE40");
                OndE40Changed();
            }
        }
        private global::System.String _dE40;
        partial void OndE40Changing(global::System.String value);
        partial void OndE40Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E41")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E41 : E30
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E41 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E41 CreateE41(global::System.Int32 id, global::System.Int32 oId)
        {
            E41 e41 = new E41();
            e41.Id = id;
            e41.OId = oId;
            return e41;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE41
        {
            get
            {
                return _dE41;
            }
            set
            {
                OndE41Changing(value);
                ReportPropertyChanging("dE41");
                _dE41 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE41");
                OndE41Changed();
            }
        }
        private global::System.String _dE41;
        partial void OndE41Changing(global::System.String value);
        partial void OndE41Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E410")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E410 : E33
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E410 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E410 CreateE410(global::System.Int32 id, global::System.Int32 oId)
        {
            E410 e410 = new E410();
            e410.Id = id;
            e410.OId = oId;
            return e410;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE410
        {
            get
            {
                return _dE410;
            }
            set
            {
                OndE410Changing(value);
                ReportPropertyChanging("dE410");
                _dE410 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE410");
                OndE410Changed();
            }
        }
        private global::System.String _dE410;
        partial void OndE410Changing(global::System.String value);
        partial void OndE410Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E411")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E411 : E33
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E411 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E411 CreateE411(global::System.Int32 id, global::System.Int32 oId)
        {
            E411 e411 = new E411();
            e411.Id = id;
            e411.OId = oId;
            return e411;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE411
        {
            get
            {
                return _dE411;
            }
            set
            {
                OndE411Changing(value);
                ReportPropertyChanging("dE411");
                _dE411 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE411");
                OndE411Changed();
            }
        }
        private global::System.String _dE411;
        partial void OndE411Changing(global::System.String value);
        partial void OndE411Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E412")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E412 : E34
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E412 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E412 CreateE412(global::System.Int32 id, global::System.Int32 oId)
        {
            E412 e412 = new E412();
            e412.Id = id;
            e412.OId = oId;
            return e412;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE412
        {
            get
            {
                return _dE412;
            }
            set
            {
                OndE412Changing(value);
                ReportPropertyChanging("dE412");
                _dE412 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE412");
                OndE412Changed();
            }
        }
        private global::System.String _dE412;
        partial void OndE412Changing(global::System.String value);
        partial void OndE412Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E413")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E413 : E34
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E413 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E413 CreateE413(global::System.Int32 id, global::System.Int32 oId)
        {
            E413 e413 = new E413();
            e413.Id = id;
            e413.OId = oId;
            return e413;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE413
        {
            get
            {
                return _dE413;
            }
            set
            {
                OndE413Changing(value);
                ReportPropertyChanging("dE413");
                _dE413 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE413");
                OndE413Changed();
            }
        }
        private global::System.String _dE413;
        partial void OndE413Changing(global::System.String value);
        partial void OndE413Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E414")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E414 : E34
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E414 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E414 CreateE414(global::System.Int32 id, global::System.Int32 oId)
        {
            E414 e414 = new E414();
            e414.Id = id;
            e414.OId = oId;
            return e414;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE414
        {
            get
            {
                return _dE414;
            }
            set
            {
                OndE414Changing(value);
                ReportPropertyChanging("dE414");
                _dE414 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE414");
                OndE414Changed();
            }
        }
        private global::System.String _dE414;
        partial void OndE414Changing(global::System.String value);
        partial void OndE414Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E415")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E415 : E35
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E415 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E415 CreateE415(global::System.Int32 id, global::System.Int32 oId)
        {
            E415 e415 = new E415();
            e415.Id = id;
            e415.OId = oId;
            return e415;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE415
        {
            get
            {
                return _dE415;
            }
            set
            {
                OndE415Changing(value);
                ReportPropertyChanging("dE415");
                _dE415 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE415");
                OndE415Changed();
            }
        }
        private global::System.String _dE415;
        partial void OndE415Changing(global::System.String value);
        partial void OndE415Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E416")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E416 : E35
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E416 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E416 CreateE416(global::System.Int32 id, global::System.Int32 oId)
        {
            E416 e416 = new E416();
            e416.Id = id;
            e416.OId = oId;
            return e416;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE415
        {
            get
            {
                return _dE415;
            }
            set
            {
                OndE415Changing(value);
                ReportPropertyChanging("dE415");
                _dE415 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE415");
                OndE415Changed();
            }
        }
        private global::System.String _dE415;
        partial void OndE415Changing(global::System.String value);
        partial void OndE415Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E417")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E417 : E35
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E417 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E417 CreateE417(global::System.Int32 id, global::System.Int32 oId)
        {
            E417 e417 = new E417();
            e417.Id = id;
            e417.OId = oId;
            return e417;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE415
        {
            get
            {
                return _dE415;
            }
            set
            {
                OndE415Changing(value);
                ReportPropertyChanging("dE415");
                _dE415 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE415");
                OndE415Changed();
            }
        }
        private global::System.String _dE415;
        partial void OndE415Changing(global::System.String value);
        partial void OndE415Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E418")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E418 : E36
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E418 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E418 CreateE418(global::System.Int32 id, global::System.Int32 oId)
        {
            E418 e418 = new E418();
            e418.Id = id;
            e418.OId = oId;
            return e418;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE415
        {
            get
            {
                return _dE415;
            }
            set
            {
                OndE415Changing(value);
                ReportPropertyChanging("dE415");
                _dE415 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE415");
                OndE415Changed();
            }
        }
        private global::System.String _dE415;
        partial void OndE415Changing(global::System.String value);
        partial void OndE415Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E419")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E419 : E36
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E419 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E419 CreateE419(global::System.Int32 id, global::System.Int32 oId)
        {
            E419 e419 = new E419();
            e419.Id = id;
            e419.OId = oId;
            return e419;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE415
        {
            get
            {
                return _dE415;
            }
            set
            {
                OndE415Changing(value);
                ReportPropertyChanging("dE415");
                _dE415 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE415");
                OndE415Changed();
            }
        }
        private global::System.String _dE415;
        partial void OndE415Changing(global::System.String value);
        partial void OndE415Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E42")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E42 : E30
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E42 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E42 CreateE42(global::System.Int32 id, global::System.Int32 oId)
        {
            E42 e42 = new E42();
            e42.Id = id;
            e42.OId = oId;
            return e42;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE42
        {
            get
            {
                return _dE42;
            }
            set
            {
                OndE42Changing(value);
                ReportPropertyChanging("dE42");
                _dE42 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE42");
                OndE42Changed();
            }
        }
        private global::System.String _dE42;
        partial void OndE42Changing(global::System.String value);
        partial void OndE42Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E420")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E420 : E36
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E420 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E420 CreateE420(global::System.Int32 id, global::System.Int32 oId)
        {
            E420 e420 = new E420();
            e420.Id = id;
            e420.OId = oId;
            return e420;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE415
        {
            get
            {
                return _dE415;
            }
            set
            {
                OndE415Changing(value);
                ReportPropertyChanging("dE415");
                _dE415 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE415");
                OndE415Changed();
            }
        }
        private global::System.String _dE415;
        partial void OndE415Changing(global::System.String value);
        partial void OndE415Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E421")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E421 : E37
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E421 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E421 CreateE421(global::System.Int32 id, global::System.Int32 oId)
        {
            E421 e421 = new E421();
            e421.Id = id;
            e421.OId = oId;
            return e421;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE415
        {
            get
            {
                return _dE415;
            }
            set
            {
                OndE415Changing(value);
                ReportPropertyChanging("dE415");
                _dE415 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE415");
                OndE415Changed();
            }
        }
        private global::System.String _dE415;
        partial void OndE415Changing(global::System.String value);
        partial void OndE415Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E422")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E422 : E37
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E422 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E422 CreateE422(global::System.Int32 id, global::System.Int32 oId)
        {
            E422 e422 = new E422();
            e422.Id = id;
            e422.OId = oId;
            return e422;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE415
        {
            get
            {
                return _dE415;
            }
            set
            {
                OndE415Changing(value);
                ReportPropertyChanging("dE415");
                _dE415 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE415");
                OndE415Changed();
            }
        }
        private global::System.String _dE415;
        partial void OndE415Changing(global::System.String value);
        partial void OndE415Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E423")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E423 : E37
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E423 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E423 CreateE423(global::System.Int32 id, global::System.Int32 oId)
        {
            E423 e423 = new E423();
            e423.Id = id;
            e423.OId = oId;
            return e423;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE415
        {
            get
            {
                return _dE415;
            }
            set
            {
                OndE415Changing(value);
                ReportPropertyChanging("dE415");
                _dE415 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE415");
                OndE415Changed();
            }
        }
        private global::System.String _dE415;
        partial void OndE415Changing(global::System.String value);
        partial void OndE415Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E43")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E43 : E31
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E43 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E43 CreateE43(global::System.Int32 id, global::System.Int32 oId)
        {
            E43 e43 = new E43();
            e43.Id = id;
            e43.OId = oId;
            return e43;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE43
        {
            get
            {
                return _dE43;
            }
            set
            {
                OndE43Changing(value);
                ReportPropertyChanging("dE43");
                _dE43 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE43");
                OndE43Changed();
            }
        }
        private global::System.String _dE43;
        partial void OndE43Changing(global::System.String value);
        partial void OndE43Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E44")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E44 : E31
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E44 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E44 CreateE44(global::System.Int32 id, global::System.Int32 oId)
        {
            E44 e44 = new E44();
            e44.Id = id;
            e44.OId = oId;
            return e44;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE44
        {
            get
            {
                return _dE44;
            }
            set
            {
                OndE44Changing(value);
                ReportPropertyChanging("dE44");
                _dE44 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE44");
                OndE44Changed();
            }
        }
        private global::System.String _dE44;
        partial void OndE44Changing(global::System.String value);
        partial void OndE44Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E45")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E45 : E31
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E45 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E45 CreateE45(global::System.Int32 id, global::System.Int32 oId)
        {
            E45 e45 = new E45();
            e45.Id = id;
            e45.OId = oId;
            return e45;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE45
        {
            get
            {
                return _dE45;
            }
            set
            {
                OndE45Changing(value);
                ReportPropertyChanging("dE45");
                _dE45 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE45");
                OndE45Changed();
            }
        }
        private global::System.String _dE45;
        partial void OndE45Changing(global::System.String value);
        partial void OndE45Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E46")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E46 : E32
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E46 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E46 CreateE46(global::System.Int32 id, global::System.Int32 oId)
        {
            E46 e46 = new E46();
            e46.Id = id;
            e46.OId = oId;
            return e46;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE46
        {
            get
            {
                return _dE46;
            }
            set
            {
                OndE46Changing(value);
                ReportPropertyChanging("dE46");
                _dE46 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE46");
                OndE46Changed();
            }
        }
        private global::System.String _dE46;
        partial void OndE46Changing(global::System.String value);
        partial void OndE46Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E47")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E47 : E32
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E47 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E47 CreateE47(global::System.Int32 id, global::System.Int32 oId)
        {
            E47 e47 = new E47();
            e47.Id = id;
            e47.OId = oId;
            return e47;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE47
        {
            get
            {
                return _dE47;
            }
            set
            {
                OndE47Changing(value);
                ReportPropertyChanging("dE47");
                _dE47 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE47");
                OndE47Changed();
            }
        }
        private global::System.String _dE47;
        partial void OndE47Changing(global::System.String value);
        partial void OndE47Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E48")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E48 : E32
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E48 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E48 CreateE48(global::System.Int32 id, global::System.Int32 oId)
        {
            E48 e48 = new E48();
            e48.Id = id;
            e48.OId = oId;
            return e48;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE48
        {
            get
            {
                return _dE48;
            }
            set
            {
                OndE48Changing(value);
                ReportPropertyChanging("dE48");
                _dE48 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE48");
                OndE48Changed();
            }
        }
        private global::System.String _dE48;
        partial void OndE48Changing(global::System.String value);
        partial void OndE48Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="E49")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class E49 : E33
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new E49 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="oId">Initial value of the OId property.</param>
        public static E49 CreateE49(global::System.Int32 id, global::System.Int32 oId)
        {
            E49 e49 = new E49();
            e49.Id = id;
            e49.OId = oId;
            return e49;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dE49
        {
            get
            {
                return _dE49;
            }
            set
            {
                OndE49Changing(value);
                ReportPropertyChanging("dE49");
                _dE49 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dE49");
                OndE49Changed();
            }
        }
        private global::System.String _dE49;
        partial void OndE49Changing(global::System.String value);
        partial void OndE49Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InheritanceDepth5WideModel", Name="O")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class O : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new O object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static O CreateO(global::System.Int32 id)
        {
            O o = new O();
            o.Id = id;
            return o;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InheritanceDepth5WideModel", "OE00", "E00")]
        public EntityCollection<E00> E00Set
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<E00>("InheritanceDepth5WideModel.OE00", "E00");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<E00>("InheritanceDepth5WideModel.OE00", "E00", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
